#!/usr/bin/env python3
# -*- coding: utf-8 -*-

REG_TAB = [
    ('B'   , 'B'   , ''),
    ('H'   , 'H'   , ''),
    ('S'   , 'S'   , ''),
    ('D'   , 'D'   , ''),
    ('Q'   , 'Q'   , ''),
    ('V8b' , 'V'   , '8B'),
    ('V16b', 'V'   , '16B'),
    ('V2h' , 'V'   , '2H'),
    ('V4h' , 'V'   , '4H'),
    ('V8h' , 'V'   , '8H'),
    ('V2s' , 'V'   , '2S'),
    ('V4s' , 'V'   , '4S'),
    ('V1d' , 'V'   , '1D'),
    ('V2d' , 'V'   , '2D'),
    ('V1q' , 'V'   , '1Q'),
    ('Vib' , 'Vidx', 'B'),
    ('Vi4b', 'Vidx', '4B'),
    ('Vih' , 'Vidx', 'H'),
    ('Vi2h', 'Vidx', '2H'),
    ('Vis' , 'Vidx', 'S'),
    ('Vid' , 'Vidx', 'D'),
]

with open('arch/aarch64/registers_advsimd_tab.go', 'w') as fp:
    print('// Code generated by "mkreg_aarch64.py", DO NOT EDIT.', file = fp)
    print(file = fp)
    print('package aarch64', file = fp)

    for pfx, ty, sfx in REG_TAB:
        print(file = fp)
        print('const (', file = fp)
        print('    %s0 %sRegister%s = iota' % (pfx, ty, sfx), file = fp)

        for i in range(1, 32):
            print('    %s%d' % (pfx, i), file = fp)
        else:
            print(')', file = fp)
